cc_validation_app/urls.py
from django.urls import path

from . import views

app_name = "cc_validation_app"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("validate/", views.validate_view, name="validate"),
    path("validate_http/<str:card_str>", views.validate_http, name="validate_http"),
    path("<int:pk>/update/", views.UpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", views.DeleteView.as_view(), name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ccv/", include("cc_validation_app.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

cc_validation_app/models.py
import re

from django.db import models

# Create your models here.
class Card(models.Model):
    number = models.CharField(("number"), max_length=23)
    expires = models.DateField(("expiry date"))
    name = models.CharField(("associated name"), max_length=100)
    cvv = models.IntegerField(("security code"))

    def __str__(self):
        plain_str = re.sub('[^0-9]', '', self.number)
        return_str_list = [plain_str[i:i+4] for i in range(0, len(plain_str), 4)]
        return_str = "-".join(return_str_list)
        return return_str

    def valid_card(self):
        # https://stackoverflow.com/a/17337613
        plain_str = re.sub('[^0-9]', '', self.number)
        verification_digit = int(plain_str[-1])
        rev_str = "".join(reversed(plain_str))
        # 1 offset because of the verification digit
        even_pos_digits = [int(rev_str[i]) for i in range(len(rev_str)) if int(i)%2==1]
        odd_pos_digits = [int(rev_str[i]) for i in range(len(rev_str)) if int(i)%2==0 and i!=0]

        processed_even_digits = [1+(2*x)%10 if 2*x>=10 else 2*x for x in even_pos_digits]

        card_validity = (sum(processed_even_digits) + sum(odd_pos_digits) + verification_digit) % 10 == 0
        return "Valid" if card_validity else "Invalid"

    def issuing_network(self):
        # TODO: Implement remaining network checks
        if self.number.startswith("34") or self.number.startswith("37"):
            return "American Express"
        elif self.number.startswith("4"):
            return "Visa"
        else:
            return "Other"

cc_validation_app/views.py
import re

from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.urls import reverse, reverse_lazy

from .models import Card

# Create your views here.
class IndexView(generic.ListView):
    template_name = "cc_validation_app/index.html"
    context_object_name = "card_list"

    def get_queryset(self):
        return Card.objects.all()

class DetailView(generic.DetailView):
    model = Card
    template_name = "cc_validation_app/detail.html"

    def get_queryset(self):
        return Card.objects.all()

class CreateView(generic.CreateView):
    model = Card
    template_name = "cc_validation_app/create.html"
    fields = ["number", "expires", "name", "cvv"]

    # https://stackoverflow.com/a/52823773
    def get_success_url(self):
        return reverse("cc_validation_app:index")

def validate_view(request):
    return render(request, "cc_validation_app/validate.html")

def validate_http(request, card_str):
    # https://stackoverflow.com/a/17337613
    plain_str = re.sub('[^0-9]', '', card_str)
    verification_digit = int(plain_str[-1])
    rev_str = "".join(reversed(plain_str))
    # 1 offset because of the verification digit
    even_pos_digits = [int(rev_str[i]) for i in range(len(rev_str)) if int(i)%2==1]
    odd_pos_digits = [int(rev_str[i]) for i in range(len(rev_str)) if int(i)%2==0 and i!=0]

    processed_even_digits = [1+(2*x)%10 if 2*x>=10 else 2*x for x in even_pos_digits]

    card_validity = (sum(processed_even_digits) + sum(odd_pos_digits) + verification_digit) % 10 == 0

    return HttpResponse(card_validity)
class UpdateView(generic.UpdateView):
    model = Card
    template_name = "cc_validation_app/create.html"
    fields = ["number", "expires", "name", "cvv"]

    # https://stackoverflow.com/a/52823773
    def get_success_url(self):
        # https://stackoverflow.com/a/66262635
        pk = self.kwargs["pk"]
        return reverse("cc_validation_app:detail", kwargs={"pk": pk})

class DeleteView(generic.DeleteView):
    model = Card
    template_name = "cc_validation_app/confirm_delete.html"
    success_url = reverse_lazy("cc_validation_app:index")

cc_validation_app/templates/cc_validation_app/components/form_combo.html
{% load tailwind_tags %}

<div class="flex flex-wrap justify-start items-center w-full gap-4">
    <label for="{{ f_id }}" class="w-full text-2xl font-mono">{{ label }}</label>
    <input type="{{ f_type }}" name="{{ name }}" maxlength="{{ max_length }}" required="" id="{{ f_id }}" value="{{ value|default_if_none:'' }}"
        class="w-full h-16 bg-zinc-900 rounded-full font-mono text-xl px-6 focus:ring-0 focus:bg-zinc-800 focus:border-zinc-600">
</div>

cc_validation_app/templates/cc_validation_app/components/head.html
{% load tailwind_tags %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }} {{ context_id }}</title>
    {% tailwind_preload_css %}
    {% tailwind_css %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
  </head>

cc_validation_app/templates/cc_validation_app/components/header.html
{% load static %}

<header class="flex justify-start items-center ml-8">
    <a href={% if top_left_icon == "arrow_back" %} "javascript:history.go(-1)" {% else %} {% url href_url %} {% endif %} class="text-3xl">
        <span class="material-symbols-outlined text-white">
            {{ top_left_icon }}
        </span>
    </a>
    <img src="{% static 'cc_validation_app/images/ccv-logo.png' %}" alt="CCV Logo" class="size-28 object-contain">
    </img>
</header>

cc_validation_app/templates/cc_validation_app/components/index_card.html
<div class="flex flex-wrap items-center justify-center content-evenly relative
    w-auto p-6 
    bg-zinc-800 border-2 border-transparent 
    hover:bg-zinc-900 hover:border-zinc-700 
    transition-all rounded-full group">
    <div class="w-full flex items-center justify-center mx-4">
        <p class="text-3xl font-mono font-semibold
            transition-all ease-out duration-200
            group-hover:opacity-0 group-hover:-translate-y-6">{{ card }}</p>
        <div class="flex-1 flex justify-end ml-6
            transition-all ease-out duration-200
            group-hover:opacity-0 group-hover:-translate-y-6">
            {% if card.valid_card == "Valid" %}
            <span class="material-symbols-outlined text-green-500">
                check
            </span>
            {% else %}
            <span class="material-symbols-outlined text-red-500">
                close
            </span>
            {% endif %}
        </div>
    </div>
    <div class="w-full flex items-center justify-center absolute px-10">
        <p class="text-xl font-mono
            opacity-0 translate-y-6
            transition-all ease-out duration-200
            group-hover:opacity-100 group-hover:translate-y-0">{{ card.name.upper }}</p>
        <p class="text-xl font-mono
            flex-1 flex justify-end
            opacity-0 translate-y-6
            transition-all ease-out duration-200
            group-hover:opacity-100 group-hover:translate-y-0">{{ card.expires | date:"m/y" }}</p>
    </div>
</div>

cc_validation_app/templates/cc_validation_app/components/main_button.html
{% load tailwind_tags %}

<a href="{% url href_url %}" class="flex items-center justify-evenly">
    <div class="flex items-center justify-evenly {{ position }} h-16 w-40 {{ size }}
        {{ bg_color }} {{ rounded }} z-10">
        <span class="material-symbols-outlined {{ text_color }}">
            {{ icon }}
        </span>
        <p class="text-base font-bold {{ text_color }}">{{ text }}</p>
    </div>
</a>

cc_validation_app/templates/cc_validation_app/components/main_button_with_pk.html
{% load tailwind_tags %}

<a href="{% url href_url pk %}" class="flex items-center justify-evenly
    relative transition-all group">
    <div class="flex items-center justify-evenly {{ position }} h-16 w-40 {{ size }}
        {{ bg_color }} {{ rounded }} z-10">
        <span class="material-symbols-outlined {{ text_color }}
            transition-all ease-out duration-200
            group-hover:opacity-0 group-hover:-translate-y-6">
            {{ icon }}
        </span>
        <p class="text-base font-bold {{ text_color }}
            transition-all ease-out duration-200
            group-hover:opacity-0 group-hover:-translate-y-6">{{ text }}</p>
    </div>
    <div class="w-full flex items-center justify-center absolute z-20">
        <span class="material-symbols-outlined {{ text_color }}
            opacity-0 translate-y-6
            transition-all ease-out duration-200
            group-hover:opacity-100 group-hover:translate-y-0">
            {{ icon }}
        </span>
    </div>
</a>

cc_validation_app/templates/cc_validation_app/confirm_delete.html
{% load ccv_templatetags %}
{% load tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
    {% head title="Delete Card" %}
    <body class="bg-zinc-950 text-neutral-100">
        {% header top_left_icon="arrow_back" href_url="cc_validation_app:index"%}
        <main class="flex justify-center items-center absolute inset-0 min-h-screen w-full -z-10">
            <form method="post" class="w-1/3 min-w-96 grid grid-cols-1 gap-4 mt-8">{% csrf_token %}
                <p class="mb-8 text-3xl font-mono">Are you sure you want to delete the card "{{ object }}"?</p>
                {{ form }}
                <input type="submit" value="Delete"
                class="flex items-center justify-evenly h-16 w-full
                bg-rose-500 rounded-full z-10
                font-bold text-xl cursor-pointer">
                <a href="javascript:history.go(-1)"
                class="flex items-center justify-evenly h-16 w-full
                bg-zinc-900 rounded-full z-10
                font-bold text-xl cursor-pointer">
                    Cancel
                </a>
            </form>
        </main>
        <footer>
        </footer>
    </body>
</html>

cc_validation_app/templates/cc_validation_app/create.html
{% load ccv_templatetags %}
{% load tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
    {% head title="New Card" %}
    <body class="bg-zinc-950 text-neutral-100">
        {% header top_left_icon="arrow_back" href_url="cc_validation_app:index"%}
        <main class="flex justify-center items-center">
            <form method="post" class="w-1/3 min-w-96 grid grid-cols-1 gap-8 mt-8">{% csrf_token %}
                <div class="flex flex-wrap justify-start items-center w-full gap-4">
                    <label for="id_number" class="w-full text-2xl font-mono">Number:</label>
                    <div class="flex justify-start items-center w-full relative">
                        <input type="text" name="{{ form.number.name }}" maxlength="23" required="" id="id_number" value="{{ form.number.value|default_if_none:'' }}"
                            class="w-full h-16 bg-zinc-900 rounded-full font-mono text-xl px-6 focus:ring-0 focus:bg-zinc-800 focus:border-zinc-600" oninput="showCardNumber()">
                        <span id="card-number-preview" class="material-symbols-outlined grow absolute right-4">
                    </div>
                </div>
                {% form_combo f_id="id_expires" label="Expiry date:" f_type="date" name=form.expires.name value=form.expires.value|date:"Y-m-d" %}
                {% form_combo f_id="id_name" label="Associated name:" f_type="text" name=form.name.name value=form.name.value max_length="100" %}
                {% form_combo f_id="id_cvv" label="Security code:" f_type="number" name=form.cvv.name value=form.cvv.value %}
                <input type="submit" value="Save"
                class="flex items-center justify-evenly fixed mx-auto inset-x-0 bottom-8 h-16 w-1/3
                bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 rounded-full z-10
                font-bold text-xl cursor-pointer">
            </form>
        </main>
        <footer>
        </footer>
    </body>
</html>
<script>
    async function showCardNumber() {
        const cardNumber = document.getElementById("id_number").value;
        const previewElement = document.getElementById("card-number-preview");

        if (cardNumber.length >= 13) {
            try {
                const response = await fetch(`/ccv/validate_http/${cardNumber}`);
                const result = await response.text();

                previewElement.textContent = result === "True" ? "check" : "close";
                previewElement.classList.toggle("text-green-500", result === "True");
                previewElement.classList.toggle("text-red-500", result === "False");

                if (result !== "True" && result !== "False") {
                    previewElement.textContent = "Non Binary, check create.html";
                }
            } catch (error) {
                previewElement.textContent = error;
            }
        } else {
            previewElement.textContent = "";
        }
    }
</script>

cc_validation_app/templates/cc_validation_app/detail.html
{% load static %}
{% load ccv_templatetags %}
{% load tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
  {% head title="Card" context_id=card.id %}
  <body class="bg-zinc-950 text-neutral-100">
    {% header top_left_icon="arrow_back" href_url="cc_validation_app:index"%}
    <main class="flex justify-center items-center absolute inset-0 min-h-screen w-full -z-10"  style="background: url(/static/cc_validation_app/images/matrix-dot-bg.png); background-size: cover; height: 100%; background-position: center">
        <div class="grid grid-cols-1 gap-6 w-full">
            <div class="flex flex-wrap items-center justify-start content-evenly
            aspect-[27/17] h-[32rem] m-8 mx-auto p-10 rounded-3xl pt-64 relative backdrop-blur-sm">
                <div class="aspect-[27/17] h-[32rem] bg-zinc-950 absolute inset-0 opacity-70 rounded-3xl border-2 border-zinc-400">

                </div>
                <div class="flex flex-wrap items-center justify-start content-evenly gap-8 z-10">
                    <p class="text-6xl font-mono font-semibold">{{ card }}</p>
                    <div class="flex-1 flex justify-end">
                        <span class="material-symbols-outlined {% if card.valid_card == "Valid" %} text-green-500 {% else %} text-red-500 {% endif %}"
                        style="font-size: 3.75rem">
                            {% if card.valid_card == "Valid" %} check {% else %} close {% endif %}
                        </span>
                    </div>
                    <p class="w-2/3 text-3xl font-mono">{{ card.name.upper }}</p>
                    <p class="flex-1 flex justify-end text-3xl font-mono">{{ card.expires | date:"m/y" }}</p>
                </div>
            </div>
            <div class="flex items-center justify-between w-[50rem] mx-auto">
                {% main_button_with_pk icon="edit" text="Edit Card" bg_color="border-2 border-amber-500 bg-zinc-950/70" position="relative" href_url="cc_validation_app:update" pk=card.id %}
                {% main_button_with_pk icon="delete" text="Delete Card" bg_color="border-2 border-rose-500 bg-zinc-950/70" position="relative" href_url="cc_validation_app:delete" pk=card.id %}
            </div>
        </div>
    </main>
  </body>
</html>

cc_validation_app/templates/cc_validation_app/index.html
{% comment %} <head>
<script src="https://cdn.tailwindcss.com"></script>
</head> {% endcomment %}

{% load ccv_templatetags %}
{% load tailwind_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  {% head title="Card Index" %}
  <body class="bg-zinc-950 text-neutral-100">
    {% header top_left_icon="apps" href_url="cc_validation_app:validate"%}
    <main class="flex justify-center items-center">
        {% if card_list %}
            <div class="grid grid-cols-1 gap-4 mt-6">
                {% for card in card_list %}
                    <a href="{% url 'cc_validation_app:detail' card.id %}">
                        {% index_card %}
                    </a>
                {% endfor %}
                <div class="bottom-spacer w-full h-24">
            </div>
        {% else %}
            <p>No cards are available.</p>
        {% endif %}
        {% main_button icon="add" text="New Card" href_url="cc_validation_app:create" %}
    </main>
    <footer>
        <div class="w-full h-48 fixed bottom-0 bg-gradient-to-t from-zinc-950 pointer-events-none">
    </footer>
  </body>
</html>

cc_validation_app/templates/cc_validation_app/update.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% comment %} form.x.value {% endcomment %}

cc_validation_app/templates/cc_validation_app/validate.html
{% load ccv_templatetags %}
{% load tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
    {% head title="Validate Card" %}
    <body class="bg-zinc-950 text-neutral-100">
        {% header top_left_icon="arrow_back"%}
        <main class="flex justify-center items-center absolute inset-0 min-h-screen w-full -z-10">
            <form method="post" class="w-1/3 min-w-96 grid grid-cols-1 gap-8 mt-8">{% csrf_token %}
                <div class="flex flex-wrap justify-start items-center w-full gap-4">
                    <div class="flex justify-start items-center w-full relative">
                        <input type="text" name="{{ form.number.name }}" maxlength="23" required="" id="id_number" value="{{ form.number.value|default_if_none:'' }}"
                            class="w-full h-16 bg-zinc-900 rounded-full font-mono text-xl px-6 focus:ring-0 focus:bg-zinc-800 focus:border-zinc-600" oninput="showCardNumber()">
                        <span id="card-number-preview" class="material-symbols-outlined grow absolute right-4">
                    </div>
                </div>
            </form>
        </main>
        <footer>
        </footer>
    </body>
</html>
<script>
    async function showCardNumber() {
        const cardNumber = document.getElementById("id_number").value;
        const previewElement = document.getElementById("card-number-preview");

        if (cardNumber.length >= 13) {
            try {
                const response = await fetch(`/ccv/validate_http/${cardNumber}`);
                const result = await response.text();

                previewElement.textContent = result === "True" ? "check" : "close";
                previewElement.classList.toggle("text-green-500", result === "True");
                previewElement.classList.toggle("text-red-500", result === "False");

                if (result !== "True" && result !== "False") {
                    previewElement.textContent = "Non Binary, check create.html";
                }
            } catch (error) {
                previewElement.textContent = error;
            }
        } else {
            previewElement.textContent = "";
        }
    }
</script>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>